# Common defaults
.defaults: &defaults
  enabled: true
  track: true

# Model dimensions
.dimensions: &model_dims
  input_size: 7
  num_classes: 5

# Common intervals
.intervals: &intervals
  plot_interval: 5
  save_interval: 10

# Common paths
.paths: &data_paths
  train_path: data/train.csv
  val_path: data/val.csv
  test_path: data/test.csv

# Base monitoring settings
.monitoring_base: &monitoring_base
  enabled: true
  log_dir: monitoring
  log_file: performance.log

# Optimizer settings
.optimizer: &optimizer_settings
  name: Adam
  params: &adam_params
    betas: [0.9, 0.999]
    eps: 1.0e-08
    lr: 0.001
    weight_decay: 0.0

# Training base settings
.training: &training_base
  batch_size: 32
  epochs: 100
  metric: f1
  device: cpu
  seed: 42

# Main configuration
best_model:
  activation: leaky_relu
  architecture:
    activation: gelu
    architecture: resnet_mlp
    batch_norm: true
    hidden_size: 128
    input_size: 7
    layers:
    - activation: gelu
      in_features: 7
      out_features: 128
      residual: false
      type: linear
    - num_features: 128
      type: batch_norm
    - activation: gelu
      in_features: 128
      out_features: 128
      residual: true
      type: linear
    - num_features: 128
      type: batch_norm
    - in_features: 128
      out_features: 5
      residual: false
      type: linear
    n_layers: 3
    num_classes: 5
  best_metric_name: f1
  best_metric_value: 0.2742516801340331
  dropout_rate: 0.0
  hidden_layers:
  - 64
  - 64
  - 64
  hidden_size: 64
  hyperparameters: null
  learning_rate: 0.0019150388839257822
  metric_name: null
  metric_value: null
  n_layers: 3
  use_batch_norm: true
  weight_decay: 0.0005323663316764337

data:
  <<: *data_paths
  target_column: target

dataloader:
  drop_last: true
  num_workers: auto
  persistent_workers: true
  pin_memory: false
  prefetch_factor: 2

device: cpu

early_stopping:
  min_delta: 0.001
  patience: 5

logging:
  directory: logs
  filename: training.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO

model:
  <<: *model_dims
  architecture_yaml: models/configs/resnet_mlp.yaml
  save_path: models/best_model.pt
  type: resnet_mlp

monitoring:
  <<: *monitoring_base
  checkpoints:
    filename: model_checkpoint.pt
    save_best: true
    <<: *intervals
  memory:
    <<: *defaults
    include_gpu: true
  metrics:
    output_file: metrics.yaml
    <<: *intervals
  performance:
    <<: *defaults
    track_throughput: true
    track_time: true

optimization:
  memory:
    gradient_accumulation_steps: 16

seed: 42

techniques:
  scheduler:
    params:
      div_factor: 25.0
      final_div_factor: 1e4
      max_lr_factor: 10.0
      pct_start: 0.3
    type: OneCycleLR
  swa:
    <<: *defaults
    lr: 0.001
    start_epoch: 75
  warmup:
    <<: *defaults
    initial_lr_factor: 0.01
    max_steps: 1000

training:
  <<: *training_base
  optimizer:
    <<: *optimizer_settings
  loss:
    label_smoothing:
      enabled: false
      factor: 0.1
    name: CrossEntropyLoss
  cpu_optimization:
    enable_mkldnn: true
    num_threads: auto
    use_bfloat16: false
  cross_validation:
    max_epochs: 20
    n_splits: 7

tuning:
  n_trials: 20
  pruning:
    min_trials_complete: 5
    warm_up_epochs: 2
